"use strict"
export const RECEIVE_QUESTION= 'RECEIVE_QUESTION'
export const SUBMIT_QUESTION = 'ANSWER_QUESTION'
export const DISPLAY_RESULTS = "DISPLAY_RESULTS"
export const NEXT_QUESTION ="NEXT_QUESTION"
export const ANSWER_SELECTED ="ANSWER_SELECTED"

